# Full CI matrix on all pushes to master branch
name: Java CI

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
    
jobs:
  # Runs current branch on Windows, Linux, macOS with multiple JDKs
  testmatrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Baseline support, Current LTS, Current GA, Current EA
        java: [8, 11, 15, 16-ea]
        os: [ubuntu-latest, macos-latest, macos-11.0, windows-latest]
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2          
      - name: Test with Maven
        run: ./mvnw test -B
      - name: Report Coverage to Coveralls
        if: contains(matrix.os, 'ubuntu') && contains(matrix.java, '8')
        run: ./mvnw test jacoco:report coveralls:report -q -Dlicense.skip=true -DrepoToken=$GITHUB_TOKEN -DserviceName=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Runs current branch on FreeBSD 10.0.1 in a VM
  # Cirrus CI tests 11.4 and 12.1 and 13.0
  testfreebsd:
    runs-on: macos-latest
    name: Test JDK 8, freebsd
    steps:
      - uses: actions/checkout@v2
      - name: Test in FreeBSD
        id: test-freebsd
        uses: vmactions/freebsd-vm@v0.0.9
        with:
          usesh: true
          prepare: |
            pkg install -y curl
            pkg install -y openjdk8
          run: |
            ./mvnw test -B

  # Runs current branch on Solaris 11.4 in a VM
  testsolaris:
    runs-on: macos-latest
    name: Test JDK 8, solaris
    steps:
      - uses: actions/checkout@v2
      - name: Test in Solaris
        id: test-solaris
        uses: vmactions/solaris-vm@v0.0.1
        with:
          prepare: |
            pkg install jdk-8
          run: |    
            ./mvnw test -B -Djacoco.skip=true
                      

  # SSH into AIX server and run test on AIX 7.1
  # Configured to pull latest from oshi master branch
  # To test on a PR, log into the aix server and create a new branch
  testaix:
    runs-on: ubuntu-latest
    name: Test JDK 8, aix
    steps:
    - name: Test in AIX
      uses: appleboy/ssh-action@master    
      with:
        host: gate.polarhome.com
        username: oshi
        password: ${{ secrets.AIX_OSHI_PW }}
        port: 775
        script_stop: true
        command_timeout: 45m
        script: |
          source .profile
          source .bashrc
          cd ~/git/oshi
          git checkout master
          git reset --hard HEAD~5
          git pull
          mvn clean test -B -Djacoco.skip=true
          