# CI on Unix OS
# Separated from main CI matrix to reduce churn on failures due to infra
name: FreeBSD CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  # Runs current branch on FreeBSD 10.0.1 in a VM
  # Cirrus CI tests 11.4, 12.3 and 13.0
  testfreebsd:
    # breaks on macos-latest
    runs-on: macos-10.15
    name: Test JDK 11, freebsd
    steps:
      - uses: actions/checkout@v3
      - name: Test in FreeBSD
        id: test-freebsd
        uses: vmactions/freebsd-vm@v0.1.7
        with:
          usesh: true
          prepare: |
            pkg install -y curl
            pkg install -y openjdk11
          run: |
            ./mvnw clean test -B -Djacoco.skip=true -Dlicense.skip=true
