name: OpenBSD CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  testopenbsd:
    runs-on: macos-13
    name: Test JDK 11, OpenBSD vm
    steps:
      - uses: actions/checkout@v3
      - name: Test on OpenBSD
        id: test-openbsd
        uses: vmactions/openbsd-vm@v0
        with:
          usesh: false
          mem: 2048
          # note default jdk for maven is 8, but some maven plugins no longer work
          # there is no meta package like eg. "jdk-11" but we can search by branch
          prepare: |
            pkg_add curl
            pkg_add jdk%11
            pkg_add maven
          run: |
            mvn clean test -B -Djacoco.skip=true
