name: OpenBSD CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  testopenbsd:
    runs-on: macos-12
    name: Test JDK 11, OpenBSD vm
    steps:
      - uses: actions/checkout@v3
      - name: Test on OpenBSD
        id: test-openbsd
        uses: vmactions/openbsd-vm@v0
        with:
          usesh: false
          mem: 2048
          prepare: |
            pkg_add curl
            pkg_add maven
          run: |
            mvn clean test -B -Djacoco.skip=true -Dlicense.skip=true
