# CI on Unix OS
# Separated from main CI matrix to reduce churn on failures due to infra
name: Solaris CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  # Runs on Solaris 11.4 x86 VM
  testsolaris:
    runs-on: macos-12
    name: Test JDK 11, Solaris VM
    steps:
      - uses: actions/checkout@v3
      - name: Test on Solaris
        id: test-solaris
        uses: vmactions/solaris-vm@v0.0.3
        with:
          run: |
            ./mvnw clean test -B -Djacoco.skip=true -Dlicense.skip=true

  # Runs current branch on Solaris 11.3 on SPARC
  # Retries flaky test once, possible junit-platform-maven-test issue
  testsolaris_sparc:
    concurrency: solaris_gcc211
    if: github.repository_owner == 'oshi'
    runs-on: ubuntu-latest
    name: Test JDK 11, Solaris SPARC
    steps:
    - name: Test in Solaris SPARC
      uses: appleboy/ssh-action@master
      with:
        host: gcc211.fsffrance.org
        username: oshi
        key: ${{ secrets.AIX_OSHI_KEY }}
        port: 22
        script_stop: true
        command_timeout: 25m
        script: |
          source .profile
          cd ~/git/oshi
          git checkout master
          git reset --hard HEAD~2
          git pull
          ./mvnw clean test -B -Djacoco.skip=true -Dlicense.skip=true || ./mvnw clean test -B -Djacoco.skip=true -Dlicense.skip=true
