# CI on Unix OS
# Separated from main CI matrix to reduce churn on failures due to infra
name: Solaris CI

concurrency: solaris_gcc211

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'

jobs:
  # Runs current branch on Solaris 11.4 in a x64 VM
  testsolaris_x64:
    if: github.repository_owner == 'oshi'
    runs-on: ubuntu-latest
    name: Test JDK 11, Solaris x64
    steps:
    - name: Test in Solaris x64
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SOLARIS_OSHI_DOMAIN }}
        username: oshi
        password: ${{ secrets.SOLARIS_OSHI_PW }}
        port: 10061
        script_stop: true
        command_timeout: 15m
        script: |
          export JAVA_HOME=~/zulu11.54.25-ca-jdk11.0.14.1-solaris
          cd ~/git/oshi
          git checkout master
          git reset --hard HEAD~2
          git pull
          mvn clean test -B -Djacoco.skip=true -Dlicense.skip=true
  # Runs current branch on Solaris 11.3 on SPARC
  # Retries flaky test once, possible junit-platform-maven-test issue
  testsolaris_sparc:
    if: github.repository_owner == 'oshi'
    runs-on: ubuntu-latest
    name: Test JDK 11, Solaris SPARC
    steps:
    - name: Test in Solaris SPARC
      uses: appleboy/ssh-action@master
      with:
        host: gcc211.fsffrance.org
        username: oshi
        key: ${{ secrets.AIX_OSHI_KEY }}
        port: 22
        script_stop: true
        command_timeout: 25m
        script: |
          source .profile
          cd ~/git/oshi
          git checkout master
          git reset --hard HEAD~2
          git pull
          ./mvnw clean test -B -Djacoco.skip=true -Dlicense.skip=true || ./mvnw clean test -B -Djacoco.skip=true -Dlicense.skip=true
